replicaCount: 2

image:
  repository: "024171229197.dkr.ecr.eu-central-1.amazonaws.com/django-app-repo"
  tag: "latest"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

env:
  DEBUG: "True"
  DB_NAME: "django_db"
  DB_USER: "dbadmin"
  DB_HOST: "django-project-db-instance.cdskuqae60p9.eu-central-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_PASSWORD: "VerySecurePass123!"

hpa:
  minReplicas: 2
  maxReplicas: 6
  targetCPU: 70
