pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - sleep
    args:
    - infinity
"""
            defaultContainer 'kaniko'
        }
    }

    environment {
        ECR_URL = "024171229197.dkr.ecr.eu-central-1.amazonaws.com/django-app-repo"
        REGION  = "eu-central-1"
        AWS_ACCESS_KEY_ID = credentials('aws-access-key')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-key')
    }

    stages {
        stage('Build & Push to ECR') {
            steps {
                container('kaniko') {
                    sh """
                    mkdir -p /kaniko/.docker
                    echo '{"credsStore":"ecr-login"}' > /kaniko/.docker/config.json
                    AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
                    AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
                    AWS_DEFAULT_REGION=${REGION} \
                    /kaniko/executor \
                      --context . \
                      --dockerfile lesson-8-9/Dockerfile \
                      --destination ${ECR_URL}:${BUILD_NUMBER}
                    """
                }
            }
        }

        stage('Update Helm Chart') {
            steps {
                sh """
                sed -i 's/tag: .*/tag: "${BUILD_NUMBER}"/' lesson-8-9/charts/django-app/values.yaml
                git config user.email "jenkins@example.com"
                git config user.name "Jenkins CI"
                git add lesson-8-9/charts/django-app/values.yaml
                git commit -m "Update image tag to ${BUILD_NUMBER} [skip ci]"
                git push origin lesson-8-9
                """
            }
        }
    }
}