apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-django
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: 024171229197.dkr.ecr.us-east-1.amazonaws.com/django-app-repo:latest
          command: ["sleep"]
          args: ["3600"]
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          resources:
            requests:
              cpu: "100m"
