apiVersion: v1
kind: Secret
metadata:
  name: django-repo-secret
  namespace: "{{ .Release.Namespace }}"
  labels:
    argocd.argoproj.io/secret-type: repository
  stringData:
    url: "{{ .Values.repoURL }}"
    type: git
